#Declare Variables
variables:
    IMAGE_NAME: grommunio/gromox-core
    IMAGE_TAG: 0.1-opensuse-leap-15-4

build_image:
    #install docker deamon, client and certs
    image: docker:22.06.0-beta.0-cli
    services:
        - docker:22.06.0-beta.0-dind
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        
    #build and push to dockerhub
    script:
       - docker run --privileged --rm tonistiigi/binfmt --install all
       - docker context create builder-context
       - docker buildx create --name builderx --driver docker-container --use builder-context
       - docker buildx build --platform linux/arm64,linux/amd64 --tag $IMAGE_NAME:$IMAGE_TAG --push .

