version: "3.9"
services:
  gromox:
    build: .
    hostname: mail.testing.com
    container_name: gromox
  db:
    image: mariadb:10
    #restart: always
    env_file:
      - db.env
    #environment:
    #  - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    #  - MARIADB_USER=${MARIADB_USER}
    #  - MARIADB_PASSWORD=${MARIADB_PASSWORD} 
    #  - MARIADB_DATABASE=${MARIADB_DATABASE}
  nginx:
    image: nginx:1.21.6
