version: "3.9"
services:
  db:
    image: mariadb:10
    container_name: db
    env_file:
      - ./env_files/db.env
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 10s
      retries: 10
      start_period: 20s
    networks:
      - gromox-network
  redis:
    container_name: redis
    image: redis:7-alpine
    networks:
      - gromox-network
  nginx:
    container_name: gromox-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "5050:443"
    env_file:
      - ./env_files/db.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gromox-network
    volumes:
      - tls-certs:/home/certificates
  admin-api:
    container_name: admin-api
    build:
      context: .
      dockerfile: admin-api.Dockerfile
    env_file:
      - ./env_files/admin_api.env
      - ./env_files/db.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gromox-network
    volumes:
      - tls-certs:/home/certificates
  mail:
    container_name: mail
    build:
      context: .
      dockerfile: mail.Dockerfile
    networks:
      - gromox-network
    env_file:
      - ./env_files/db.env
    volumes:
      - tls-certs:/home/certificates
  delivery:
    container_name: delivery
    build:
      context: .
      dockerfile: delivery.Dockerfile
    networks:
      - gromox-network
    env_file:
      - ./env_files/db.env
    volumes:
      - tls-certs:/home/certificates
  gromox-http:
    build:
      context: .
      dockerfile: http.Dockerfile
    container_name: gromox-http
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gromox-network
    env_file:
      - ./env_files/db.env
    volumes:
      - tls-certs:/home/certificates
  grom-web:
    build:
      context: .
      dockerfile: grom-web.Dockerfile
    container_name: grom-web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5051:443"
    networks:
      - gromox-network
    env_file:
      - ./env_files/db.env
    volumes:
      - tls-certs:/home/certificates
networks:
  gromox-network: 
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
volumes:
  tls-certs:
      driver_opts:
        type: none
        device: ${PWD}/tls_keys
        o: bind
