version: "3.9"
services:
  core:
    #image: grommunio/gromox-core:0.3-opensuse-leap-15-4
    build: ./gromox-core
    volumes:
      - /srv/docker/gromox/certificates:/home/certificates
      - /srv/docker/gromox/gromox-services:/home/gromox-services
      - /srv/docker/gromox/nginx:/home/nginx
      - /srv/docker/gromox/data:/var/lib/gromox/
    environment:
      - MARIADB_USER=grommunio
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=grommunio
      - DB_HOST=db
      - ADMIN_PASS=admin
      - FQDN=example.com
      - S6_VERBOSITY=3
    ports:
      - '443:443'
      - '11334:11334'
    depends_on:
      db:
        condition: service_started
    networks:
      proxynet:
        aliases: 
          - grommunio
      default:


  db:
    image: mariadb
    environment:
      - MARIADB_DATABASE=grommunio
      - MARIADB_USER=grommunio
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_ROOT_HOST=%
    volumes:
      - /srv/docker/gromox/db:/var/lib/mysql
    networks:
      default:
        aliases:
          - db

  admin:
    #image: grommunio/grommunio-admin:0.1-opensuse-leap-15-4
    build: ./grommunio-admin
    volumes:
      - /srv/docker/gromox/certificates:/home/certificates
      - /srv/docker/gromox/plugins:/home/plugins
      - /srv/docker/gromox/links:/home/links
      - /srv/docker/gromox/nginx:/home/nginx
      - /srv/docker/gromox/data:/var/lib/gromox/
    environment:
      - MARIADB_USER=grommunio
      - MARIADB_PASSWORD=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=grommunio
      - DB_HOST=db
      - ADMIN_PASS=admin
      - FQDN=mail.route27.test
      - S6_VERBOSITY=3
    ports:
      - '8443:8443'
    depends_on:
      db:
        condition: service_started
    networks:
      proxynet:
        aliases: 
          - grommunio-admin
      default:


#volumes:
#  db:
#    driver: local

networks:
  # This network has been created separately
  proxynet:
    external: true
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd12:3456:789a:1::/64"
