apiVersion: apps/v1
kind: Deployment
metadata:
  name: gromox-deployment
  labels:
    app: gromox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gromox
  template:
    metadata:
      labels:
        app: gromox
    spec:
      containers:
      - name: gromox-event
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/event"]
        ports:
        - containerPort: 33333 
        envFrom:
        - configMapRef:
            name: db-config
      - name: gromox-timer
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/timer"]
        ports:
        - containerPort: 6666 
        envFrom:
        - configMapRef:
            name: db-config
      - name: gromox-zcore
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/zcore"]
        envFrom:
        - configMapRef:
            name: db-config
      - name: gromox-midb
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/midb"]
        envFrom:
        - configMapRef:
            name: db-config
      - name: gromox-nginx
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
      - name: gromox-http
        image: olam1k0/gromox-suse:latest
        command: ['sh', '-c', "/scripts/db.sh && /usr/libexec/gromox/http"]
        ports:
        - containerPort: 10080
        - containerPort: 10443
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - name: ssl-volume
          mountPath: /home/certificates
      volumes:
      - name: ssl-volume
        configMap:
          name: ssl-config
---
apiVersion: v1
kind: Service
metadata:
  name: gromox-service
spec:
  selector:
    app: gromox
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
